export default [
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        FormData: 'readonly',
        // Node.js globals (for scripts)
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        // ES modules
        import: 'readonly',
        export: 'readonly',
        // Game-specific globals (defined in src/ files with var)
        canvas: 'readonly',
        Actor: 'readonly',
        renderScale: 'readonly',
        mapMargin: 'readonly',
        mapPad: 'readonly',
        mapWidth: 'readonly',
        mapHeight: 'readonly',
        screenWidth: 'readonly',
        screenHeight: 'readonly',
        getDevicePixelRatio: 'readonly',
        newChildObject: 'readonly',
        tileSize: 'readonly',
        map: 'readonly',
        midTile: 'readonly',
        setDirFromEnum: 'readonly',
        renderer_list: 'readonly',
        renderer: 'readonly',
        // Game entities and state
        pacman: 'readonly',
        blinky: 'readonly',
        pinky: 'readonly',
        inky: 'readonly',
        clyde: 'readonly',
        ghosts: 'readonly',
        actors: 'readonly',
        audio: 'readonly',
        atlas: 'readonly',
        fruit: 'readonly',
        energizer: 'readonly',
        vcr: 'readonly',
        state: 'readonly',
        level: 'readonly',
        gameMode: 'readonly',
        practiceMode: 'readonly',
        // Direction constants
        DIR_UP: 'readonly',
        DIR_DOWN: 'readonly',
        DIR_LEFT: 'readonly',
        DIR_RIGHT: 'readonly',
        // Game mode constants
        GAME_PACMAN: 'readonly',
        GAME_MSPACMAN: 'readonly',
        GAME_COOKIE: 'readonly',
        GAME_OTTO: 'readonly',
        // Step constants
        STEP_PACMAN: 'readonly',
        STEP_GHOST: 'readonly',
        STEP_PACMAN_FRIGHT: 'readonly',
        STEP_GHOST_FRIGHT: 'readonly',
        STEP_GHOST_TUNNEL: 'readonly',
        STEP_ELROY1: 'readonly',
        STEP_ELROY2: 'readonly',
        // Ghost state constants
        GHOST_OUTSIDE: 'readonly',
        GHOST_EATEN: 'readonly',
        GHOST_GOING_HOME: 'readonly',
        GHOST_ENTERING_HOME: 'readonly',
        GHOST_PACING_HOME: 'readonly',
        GHOST_LEAVING_HOME: 'readonly',
        GHOST_CMD_CHASE: 'readonly',
        GHOST_CMD_SCATTER: 'readonly',
        // Game functions
        switchState: 'readonly',
        getRandomInt: 'readonly',
        turboMode: 'readonly',
        deadState: 'readonly',
        scriptState: 'readonly',
        ghostCommander: 'readonly',
        ghostReleaser: 'readonly',
        addScore: 'readonly',
        backupCheats: 'readonly',
        clearCheats: 'readonly',
        restoreCheats: 'readonly',
        // Direction/rotation functions
        getClockwiseAngleFromTop: 'readonly',
        rotateLeft: 'readonly',
        rotateRight: 'readonly',
        rotateAboutFace: 'readonly',
        getTurnClosestToTarget: 'readonly',
        getOpenTiles: 'readonly',
        isNextTileFloor: 'readonly',
        // Drawing functions
        drawGhostSprite: 'readonly',
        drawPacmanSprite: 'readonly',
        drawMsPacmanSprite: 'readonly',
        drawCookiemanSprite: 'readonly',
        drawMonsterSprite: 'readonly',
        drawOttoSprite: 'readonly',
        drawMsOttoSprite: 'readonly',
        drawGiantPacmanSprite: 'readonly',
        drawPacPoints: 'readonly',
        drawMsPacPoints: 'readonly',
        drawCherry: 'readonly',
        drawStrawberry: 'readonly',
        drawOrange: 'readonly',
        drawApple: 'readonly',
        drawMelon: 'readonly',
        drawGalaxian: 'readonly',
        drawBell: 'readonly',
        drawKey: 'readonly',
        drawPretzel: 'readonly',
        drawPear: 'readonly',
        drawBanana: 'readonly',
        drawCookie: 'readonly',
        drawCookieFlash: 'readonly',
        drawSnail: 'readonly',
        drawHeartSprite: 'readonly',
        // Game modules
        inGameMenu: 'readonly',
        hud: 'readonly',
        executive: 'readonly',
        readyNewState: 'readonly',
        // Game states
        homeState: 'readonly',
        learnState: 'readonly',
        newGameState: 'readonly',
        readyRestartState: 'readonly',
        playState: 'readonly',
        finishState: 'readonly',
        overState: 'readonly',
        // Game variables
        extraLives: 'readonly',
        highScores: 'readonly',
        paths: 'readonly',
        elroyTimer: 'readonly',
        galagaStars: 'readonly',
        cutscenes: 'readonly',
        setFruitFromGameMode: 'readonly',
        // Canvas context (may be used globally in some files)
        ctx: 'readonly',
        // Graph functions (if used)
        exit_graph: 'readonly',
        enter_graph: 'readonly',
        // Performance API
        performance: 'readonly',
        // Other game functions
        getPointerPos: 'readonly',
        getGameName: 'readonly',
        getGameDescription: 'readonly',
        getGhostNames: 'readonly',
        getGhostDrawFunc: 'readonly',
        getPlayerDrawFunc: 'readonly',
        getScoreIndex: 'readonly',
        getScore: 'readonly',
        getHighScore: 'readonly',
        getLevelAct: 'readonly',
        getActColor: 'readonly',
        getActRange: 'readonly',
        getCookieActColor: 'readonly',
        getMsPacActColor: 'readonly',
        getSpriteFuncFromFruitName: 'readonly',
        getRandomColor: 'readonly',
        // VCR constants
        VCR_NONE: 'readonly',
        VCR_RECORD: 'readonly',
        // Browser APIs
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        PointerEvent: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        MutationObserver: 'readonly',
        Blob: 'readonly',
        Audio: 'readonly',
        // Game classes
        Button: 'readonly',
        Ghost: 'readonly',
        Player: 'readonly',
        Menu: 'readonly',
        ToggleButton: 'readonly',
      },
    },
    rules: {
      // Basic syntax checking
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': 'off', // Allow console in this project
      'no-undef': 'error',
      'no-unreachable': 'error',
      'no-extra-semi': 'error',
      'no-unexpected-multiline': 'error',
    },
  },
];
