// Auto-generated by scripts/generate-onchain-config.mjs
window.BaseManOnchainConfig = {
  "registryAddress": "0x2fd9492E5f0F9559152bB5d4d23843072bCF17E2",
  "chainId": 8453,
  "scoreEndpoint": "/api/score-sign",
  "questEndpoint": "/api/quest-sign",
  "paymasterUrl": "/api/paymaster-proxy",
  "bundlerUrl": "https://api.developer.coinbase.com/rpc/v1/base/EUGYHs6dwJGFywyG2wcArmuw0tWn80v1"
};
