// Auto-generated by scripts/generate-onchain-config.mjs
export const onchainConfig = {
  "registryAddress": "0x9B00ab2D2dCAcd92Ba6211141Cad86C7D6ac8Fb4",
  "chainId": 84532,
  "scoreEndpoint": "/api/score-sign",
  "questEndpoint": "/api/quest-sign"
};
