// Auto-generated by scripts/generate-onchain-config.mjs
window.BaseManOnchainConfig = {
  "registryAddress": "0x9b00ab2d2dcacd92ba6211141cad86c7d6ac8fb4",
  "chainId": 84532,
  "scoreEndpoint": "/api/score-sign",
  "questEndpoint": "/api/quest-sign",
  "paymasterUrl": "/api/paymaster-proxy",
  "bundlerUrl": "https://api.developer.coinbase.com/rpc/v1/base-sepolia/EUGYHs6dwJGFywyG2wcArmuw0tWn80v1"
};
